# App config
DATA_SOURCE = "emotiv"  # Using Emotiv EPOC as the only source

SAMPLE_RATE = 128  # Hz
N_CHANNELS = 14  # EPOC has 14 EEG channels

BANDPASS = (1.0, 40.0)  # Hz
NOTCH = 50.0  # Hz
ARTIFACT_UV = 120.0  # artifact gate (abs amplitude)

WIN_SEC = 1.5
HOP_SEC = 0.5
BANDS = [(4, 8), (8, 12), (12, 16), (16, 22), (22, 30)]

CONF_THRESHOLD = 0.60
MAJORITY_K = 5
NOOP_LABEL = "noop"

TRIALS_PER_CLASS = 8
BASELINE_SEC = 1.5
TASK_SEC = 4.0
REST_SEC = 2.0

TURN_HOLD_FRAMES = 2
DEADZONE_SEC = 0.6
MAX_SPEED = 180.0
TURN_RATE = 140.0

# Pseudo-3D Game constants
SCREEN_WIDTH = 320
SCREEN_HEIGHT = 180
ROAD_DRAW_DISTANCE = 120
ROAD_PERSPECTIVE_FACTOR = 150
ROAD_SCALE_FACTOR = 160
ROAD_BASE_HEIGHT = 60
ROAD_COLOR_BASE = (50, 130, 50)
ROAD_COLOR_DISTANCE_FACTOR = 3
ROAD_COLOR_Z_FACTOR = 20
ROAD_COLOR_SINE_FACTOR = 30

# Road generation constants
ROAD_CURVE_FREQUENCY_1 = 17
ROAD_CURVE_AMPLITUDE_1 = 200
ROAD_CURVE_FREQUENCY_2 = 8
ROAD_CURVE_AMPLITUDE_2 = 170

ROAD_INCLINE_FREQUENCY_1 = 13
ROAD_INCLINE_AMPLITUDE_1 = 80
ROAD_INCLINE_FREQUENCY_2 = 7
ROAD_INCLINE_AMPLITUDE_2 = 120
ROAD_INCLINE_BASE = 200

# Player constants
PLAYER_MAX_VELOCITY = 20
PLAYER_MIN_VELOCITY = -10
PLAYER_MAX_ANGLE = 0.8
PLAYER_MIN_ANGLE = -0.8
PLAYER_ACCELERATION_FORCE = 4
PLAYER_BRAKE_FORCE = 1
PLAYER_DRAG_FACTOR = 0.5
PLAYER_STEERING_FACTOR = 10

# Collision constants
COLLISION_THRESHOLD = 280
COLLISION_MIN_VELOCITY = 5
