"""HTML report writer with visualization."""

from pathlib import Path
from typing import List
import pandas as pd

from modulus.domain.entities import MetricSet


class HtmlReportWriter:
    """Writes evaluation metrics to HTML format with tables."""

    def write(
        self,
        metrics: List[MetricSet],
        output_path: str,
        **kwargs,
    ) -> None:
        """
        Write metrics to HTML file with styled tables.

        Args:
            metrics: List of MetricSet entities
            output_path: Path to output HTML file
            **kwargs: Additional parameters (title, etc.)
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Convert metrics to DataFrame
        rows = []
        for metric_set in metrics:
            row = {
                "Model": metric_set.model_name,
                "Split": metric_set.split,
                **metric_set.metrics,
            }
            rows.append(row)

        df = pd.DataFrame(rows)

        # Generate HTML
        title = kwargs.get("title", "Model Evaluation Report")
        html_content = self._generate_html(df, title)

        with open(output_path, "w") as f:
            f.write(html_content)

    def _generate_html(self, df: pd.DataFrame, title: str) -> str:
        """Generate HTML content with styling."""

        # Convert DataFrame to HTML table
        table_html = df.to_html(index=False, classes="metrics-table", border=0)

        html_template = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 40px;
            background-color: #f5f5f5;
        }}
        h1 {{
            color: #333;
            border-bottom: 3px solid #4CAF50;
            padding-bottom: 10px;
        }}
        .metrics-table {{
            width: 100%;
            border-collapse: collapse;
            background-color: white;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            margin-top: 20px;
        }}
        .metrics-table th {{
            background-color: #4CAF50;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: bold;
        }}
        .metrics-table td {{
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }}
        .metrics-table tr:hover {{
            background-color: #f5f5f5;
        }}
        .metrics-table tr:last-child td {{
            border-bottom: none;
        }}
        .footer {{
            margin-top: 40px;
            color: #666;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    {table_html}
    <div class="footer">
        <p>Generated by Modulus Pipeline</p>
    </div>
</body>
</html>
"""
        return html_template
